### ISSUE TITLE
[Bug] System — Crash — Downloading 101 Webpages With the Same Name Can Cause the System to Crash

### ISSUE THREAD

**Issue by yeymour** [lmmx/tabsave#2]
When downloading over 101 webpages that have the same name when saved, the file after the 101st file will not be saved and no other files with that name will be able to be written which causes save prompts to stack up until the system crashes. 

The last file saved will appear, for example:

"
Filename (100)
"

I'm not quite sure if this is just an issue with windows rather than this extension. However, it would be nice if it had some sort of check for this to prevent this system crash. 

Note 1: When this occurred for me I was downloading 196 webpages.

Note 2: Its easy enough to work around by only downloading 100 webpages at a time though since it can cause a system crash I thought I would mention it. 

Edit: Changed the quoted text to adjust for the auto-formatting I was unaware of.

**Comment by lmmx** [comment]
Ah, how strange! That'll be a limit with the `chrome.downloads` API's limit, and since I don't know what sort of delay would be a suitable workaround (or whether the figure of 100 may increase in future versions of Chrome) I'd rather leave it than try and script some solution.

The source code is here if you want to have a go at a solution that works for your needs :smile:
